version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8443:8443"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"